report_app/report/urls.py
from django.urls import path

from .views import ReportUpdateView, ReportDeleteView, ReportListView, ReportCreateView, \
    ReportDetailView

urlpatterns = [
    path('report_create/', ReportCreateView.as_view(), name='report_create'),
    path('report_detail/<int:pk>', ReportDetailView.as_view(), name='report_detail'),
    path('report_update/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('report_delete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('', ReportListView.as_view(), name='report_list'),
]

report_app/report_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path("", include('report.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report_app/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import UserDetail, UserCreate, UserList, UserUpdate, password_reset_request
from .views import login_view, logout_view

urlpatterns = [
    path('user_list/', UserList.as_view(), name='users_list'),
    path('user-detail/<int:pk>', UserDetail.as_view(), name='user_detail'),
    path('auth/sign-up/', UserCreate.as_view(), name='user_create'),
    path('user_update/<int:pk>', UserUpdate.as_view(), name='user_update'),
    path('auth/login/', login_view, name='login'),
    path('auth/logout/', logout_view, name='logout'),
    path('password_reset/', password_reset_request, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/p_r_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/r_token.html'),
         name='password_reset_confirm'),
    path('reset/done',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/r_done.html'),
         name='password_reset_complete'),

]

report_app/report/models.py
from django.db import models
from django.urls import reverse

from  subscriber.models import Subscriber

from users.models import User


# Create your models here.
class Locality(models.Model):
    name = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Report(models.Model):
    REPORT_TYPE = (
        ('мідь', 'Мідь'),
        ('pon', 'Pon'),
    )

    subscriber = models.ForeignKey(Subscriber, null=True, blank=True, on_delete=models.SET_NULL)
    city = models.ForeignKey(Locality, on_delete=models.CASCADE)
    street = models.CharField(max_length=50)
    house = models.CharField(max_length=10)
    apartment = models.CharField(max_length=10)
    report_type = models.CharField(max_length=10, choices=REPORT_TYPE, default='мідь')
    cable_fo = models.IntegerField(null=True, blank=True)
    cable_utp = models.IntegerField(null=True, blank=True)
    router = models.BooleanField(default=False)
    tv = models.BooleanField(default=False)
    connection_date = models.DateField(null=False, blank=True)
    executor = models.ForeignKey(User, related_name='executor', null=True, blank=True, on_delete=models.SET_NULL)
    partner = models.ForeignKey(User, related_name='partner', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.report_type} {self.city} {self.street} {self.house} {self.apartment} {self.cable_fo} {self.cable_utp} {self.router} {self.tv}"

    def get_absolute_url(self):
        return reverse('report_detail', kwargs={'pk': self.pk})

report_app/report/forms.py
import datetime

from django import forms
from django.utils.datetime_safe import date

from report.models import Report

from subscriber.models import Subscriber


class ReportCreateForm(forms.ModelForm):
    connection_date = forms.DateField(
        label="Дата підключення",  # Нова назва поля
        widget=forms.DateInput(
            attrs={'type': 'date', 'class': 'form-control', 'placeholder': 'ДД.ММ.РРРР'},
            format='%d.%m.%Y',
        ),
        input_formats=['%d.%m.%Y'],
        initial=date.today()
    )
    subscriber = forms.ModelChoiceField(
        label="Виберіть абонента",  # Нова назва поля
        queryset=Subscriber.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Report
        fields = ['subscriber', 'city', 'street', 'house', 'apartment', 'report_type', 'cable_fo', 'cable_utp',
                  'router', 'tv', 'connection_date', 'executor', 'partner']
        widgets = {
            'subscriber': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'house': forms.TextInput(attrs={'class': 'form-control'}),
            'apartment': forms.TextInput(attrs={'class': 'form-control'}),
            'report_type': forms.Select(attrs={'class': 'form-control'}),
            'cable_fo': forms.NumberInput(attrs={'class': 'form-control'}),
            'cable_utp': forms.NumberInput(attrs={'class': 'form-control'}),
            # 'connection_date': forms.DateInput(attrs={'class': 'form-control', , 'name': "connection_date", 'placeholder': "ДД.ММ.РРРР", 'value': datetime.date}),
            'executor': forms.Select(attrs={'class': 'form-control'}),
            'partner': forms.Select(attrs={'class': 'form-control'})

        }

report_app/report/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from .forms import ReportCreateForm
from .models import Report


# Create your views here.

class ReportCreateView(CreateView):
    template_name = 'report/report_create.html'
    form_class = ReportCreateForm


class ReportDetailView(DetailView):
    template_name = 'report/report_detail.html'
    model = Report
    context_object_name = 'report'


class ReportListView(ListView):
    template_name = 'report/report_list.html'
    model = Report
    context_object_name = 'reports'
    paginate_by = 10


class ReportUpdateView(UpdateView):
    template_name = 'report/report_update.html'
    model = Report
    fields = "__all__"


class ReportDeleteView(DeleteView):
    model = Report
    template_name = 'report/report_delete.html'
    success_url = reverse_lazy('report_list')

report_app/report/templates/report/report_create.html
{% extends 'base.html' %}
{% block content %}
<div class="form-group">
    <h1>Create Report</h1>
    <form class="mx-1 mx-md-1" novalidate method="post" action="{% url 'report_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-flex justify-content-center mx-4 mt-2 mb-3 mb-lg-4">
            <button type="submit" class="btn btn-primary btn-lg">Зберегти</button>
        </div>
    </form>
</div>
{% endblock %}

report_app/report/templates/report/report_delete.html
{% extends "base.html" %}

{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
        <div class="row d-flex justify-content-left align-items-top h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-left">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Видалення Звіту</p>

                                <form class="mx-1 mx-md-4" method="post">{% csrf_token %}
                                    <p>Are you sure you want to delete "{{ object }}"?</p>
                                    {{ form }}
                                    <input type="submit" value="Confirm">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

report_app/report/templates/report/report_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h1>Звіт:</h1>
    <div class="card">
        <div class="card-body">
            {{ report }}
        </div>
    </div>
    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
        <a class="btn btn-danger btn-lg" href="{% url 'report_update' report.pk %}">Редагувати</a>
    </div>
    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
        <a class="btn btn-danger btn-lg" href="{% url 'report_delete' report.pk %}">Видалити</a>
    </div>
</div>
{% endblock %}

report_app/report/templates/report/report_list.html
{% extends "base.html" %}
{% block content %}
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
    </style>
<div class="container">
    <h1>Звіти про підключення</h1>
    <table border="1">
        <thead>
            <tr>
                <th>Абонент</th>
                <th>Населений пункт</th>
                <th>Вул.</th>
                <th>Буд.</th>
                <th>кв.</th>
                <th>Тип</th>
                <th>FO</th>
                <th>UTP</th>
                <th>Роутер</th>
                <th>ТВ</th>
                <th>Дата</th>
                <th>Виконавець</th>
                <th>Напарник</th>
                <th>Редагувати</th>
                <th>Видалити</th>

            </tr>
        </thead>
        <tbody>
            {% for report in reports %}
            <tr>
                <td>{{ report.subscriber.first_name }} {{ report.subscriber.last_name }}</td>
                <td>{{ report.city.name }}</td>
                <td>{{ report.street }}</td>
                <td>{{ report.house }}</td>
                <td>{{ report.apartment }}</td>
                <td>{{ report.get_report_type_display }}</td>
                <td>{{ report.cable_fo }}</td>
                <td>{{ report.cable_utp }}</td>
                <td>{{ report.router }}</td>
                <td>{{ report.tv }}</td>
                <td>{{ report.connection_date|date:"d.m.Y" }}</td>
                <td>{{ report.executor }}</td>
                <td>{{ report.partner }}</td>
                <td><a href="{% url 'report_update' report.pk %}">редагувати</a></td>
                <td><a href="{% url 'report_delete' report.pk %}">видалити</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include 'pagination.html' %}
</div>
{% endblock %}

report_app/report/templates/report/report_update.html
{% extends "base.html" %}

{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
        <div class="row d-flex justify-content-left align-items-top h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-left">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Update report</p>
                                <form class="mx-1 mx-md-4" novalidate method="post"
                                      action="{% url 'report_update' report.pk %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                        <button type="submit" class="btn btn-primary btn-lg">Зберегти</button>
                                    </div>
                                </form>
                                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                    <a class="btn btn-danger btn-lg" href="{% url 'report_delete' report.pk %}">Видалити</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}